name: null
favicon: null
layout_spectrum: 0.75973
typography_spectrum: 0.54043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23232c'
    - '#f9f7fa'
    - '#7a3f39'
    - '#b39b78'
    - '#f4aca6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
